package com.deepzub.footify.presentation.football_wordle.model

val FOOTBALLER_LIST: List<FootballerInfo> = listOf(

    FootballerInfo("YAMAL", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("BELLINGHAM", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("HAALAND", "Norway", "https://flagsapi.com/NO/flat/64.png"),
    FootballerInfo("MBAPPE", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("VINICIUS", "Brazil", "https://flagsapi.com/BR/flat/64.png"),

    FootballerInfo("SAKA", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("PEDRI", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("WIRTZ", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("MUSIALA", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("VALVERDE", "Uruguay", "https://flagsapi.com/UY/flat/64.png"),

    FootballerInfo("PALMER", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("RICE", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("ISAK", "Sweden", "https://flagsapi.com/SE/flat/64.png"),
    FootballerInfo("RODRI", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("ALVAREZ", "Argentina", "https://flagsapi.com/AR/flat/64.png"),

    FootballerInfo("OLISE", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("DOUE", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("CAICEDO", "Ecuador", "https://flagsapi.com/EC/flat/64.png"),
    FootballerInfo("RODRYGO", "Brazil", "https://flagsapi.com/BR/flat/64.png"),
    FootballerInfo("RAPHINHA", "Brazil", "https://flagsapi.com/BR/flat/64.png"),

    FootballerInfo("DEMBELE", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("ODEGAARD", "Norway", "https://flagsapi.com/NO/flat/64.png"),
    FootballerInfo("CUBARSI", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("SALIBA", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("VITINHA", "Portugal", "https://flagsapi.com/PT/flat/64.png"),

    FootballerInfo("SZOBOSZLAI", "Hungary", "https://flagsapi.com/HU/flat/64.png"),
    FootballerInfo("HAKIMI", "Morocco", "https://flagsapi.com/MA/flat/64.png"),
    FootballerInfo("BASTONI", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("EKITIKE", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("GVARDIOL", "Croatia", "https://flagsapi.com/HR/flat/64.png"),

    FootballerInfo("MARMOUSH", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("TCHOUAMENI", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("BARELLA", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("THURAM", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("GYOKERES", "Sweden", "https://flagsapi.com/SE/flat/64.png"),

    FootballerInfo("KANE", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("BARCOLA", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("SESKO", "Slovenia", "https://flagsapi.com/SI/flat/64.png"),
    FootballerInfo("SIMONS", "Netherlands", "https://flagsapi.com/NL/flat/64.png"),
    FootballerInfo("DIAZ", "Colombia", "https://flagsapi.com/CO/flat/64.png"),

    FootballerInfo("GAKPO", "Netherlands", "https://flagsapi.com/NL/flat/64.png"),
    FootballerInfo("OSIMHEN", "Nigeria", "https://flagsapi.com/NG/flat/64.png"),
    FootballerInfo("LEAO", "Portugal", "https://flagsapi.com/PT/flat/64.png"),
    FootballerInfo("PACHO", "Colombia", "https://flagsapi.com/CO/flat/64.png"),
    FootballerInfo("KOUNDE", "France", "https://flagsapi.com/FR/flat/64.png"),

    FootballerInfo("DIAS", "Portugal", "https://flagsapi.com/PT/flat/64.png"),
    FootballerInfo("HAVERTZ", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("HUIJSEN", "Netherlands", "https://flagsapi.com/NL/flat/64.png"),
    FootballerInfo("GAVI", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("CAMAVINGA", "France", "https://flagsapi.com/FR/flat/64.png"),

    FootballerInfo("BALDE", "Senegal", "https://flagsapi.com/SN/flat/64.png"),
    FootballerInfo("SANCET", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("CUNHA", "Brazil", "https://flagsapi.com/BR/flat/64.png"),
    FootballerInfo("REIJNDERS", "Netherlands", "https://flagsapi.com/NL/flat/64.png"),
    FootballerInfo("ZUBIMENDI", "Argentina", "https://flagsapi.com/AR/flat/64.png"),

    FootballerInfo("LOOKMAN", "Nigeria", "https://flagsapi.com/NG/flat/64.png"),
    FootballerInfo("TONALI", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("KONATE", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("OLMO", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("YORO", "France", "https://flagsapi.com/FR/flat/64.png"),

    FootballerInfo("PAVLOVIC", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("MARTINELLI", "Brazil", "https://flagsapi.com/BR/flat/64.png"),
    FootballerInfo("TIMBER", "Netherlands", "https://flagsapi.com/NL/flat/64.png"),
    FootballerInfo("MAINOO", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("SAVINHO", "Brazil", "https://flagsapi.com/BR/flat/64.png"),

    FootballerInfo("EDERSON", "Brazil", "https://flagsapi.com/BR/flat/64.png"),
    FootballerInfo("NETO", "Brazil", "https://flagsapi.com/BR/flat/64.png"),
    FootballerInfo("DOKU", "Belgium", "https://flagsapi.com/BE/flat/64.png"),
    FootballerInfo("ONANA", "Cameroon", "https://flagsapi.com/CM/flat/64.png"),
    FootballerInfo("FRIMPONG", "Netherlands", "https://flagsapi.com/NL/flat/64.png"),

    FootballerInfo("KULUSEVSKI", "Sweden", "https://flagsapi.com/SE/flat/64.png"),
    FootballerInfo("OPENDA", "Belgium", "https://flagsapi.com/BE/flat/64.png"),
    FootballerInfo("ROMERO", "Argentina", "https://flagsapi.com/AR/flat/64.png"),
    FootballerInfo("UPAMECANO", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("AMRABAT", "Morocco", "https://flagsapi.com/MA/flat/64.png"),

    FootballerInfo("PULISIC", "USA", "https://flagsapi.com/US/flat/64.png"),
    FootballerInfo("RASHFORD", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("DIMARCO", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("SALAH", "Egypt", "https://flagsapi.com/EG/flat/64.png"),
    FootballerInfo("GARNACHO", "Argentina", "https://flagsapi.com/AR/flat/64.png"),

    FootballerInfo("KERKEZ", "Hungary", "https://flagsapi.com/HU/flat/64.png"),
    FootballerInfo("CHERKI", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("RETEGUI", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("NUNEZ", "Uruguay", "https://flagsapi.com/UY/flat/64.png"),
    FootballerInfo("KUDUS", "Ghana", "https://flagsapi.com/GH/flat/64.png"),

    FootballerInfo("DIALLO", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("ADEYEMI", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("UGARTE", "Uruguay", "https://flagsapi.com/UY/flat/64.png"),
    FootballerInfo("GUIRASSY", "Guinea", "https://flagsapi.com/GN/flat/64.png"),
    FootballerInfo("KIMMICH", "Germany", "https://flagsapi.com/DE/flat/64.png"),

    FootballerInfo("MADDISON", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("ASENCIO", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("UDOGIE", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("GREENWOOD", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("BONIFACE", "Nigeria", "https://flagsapi.com/NG/flat/64.png"),

    FootballerInfo("MADUEKE", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("GALLAGHER", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("RUIZ", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("WATKINS", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("DONNARUMMA", "Italy", "https://flagsapi.com/IT/flat/64.png"),

    FootballerInfo("BOWEN", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("RAYA", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("SOLANKE", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("KOBEL", "Switzerland", "https://flagsapi.com/CH/flat/64.png"),
    FootballerInfo("PORRO", "Spain", "https://flagsapi.com/ES/flat/64.png"),

    FootballerInfo("TIELEMANS", "Belgium", "https://flagsapi.com/BE/flat/64.png"),
    FootballerInfo("ENDRICK", "Brazil", "https://flagsapi.com/BR/flat/64.png"),
    FootballerInfo("TEL", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("DURAN", "Colombia", "https://flagsapi.com/CO/flat/64.png"),
    FootballerInfo("HOJLUND", "Denmark", "https://flagsapi.com/DK/flat/64.png"),

    FootballerInfo("ANTONY", "Brazil", "https://flagsapi.com/BR/flat/64.png"),
    FootballerInfo("CALAFIORI", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("BISSECK", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("KONSA", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("FRATTESI", "Italy", "https://flagsapi.com/IT/flat/64.png"),

    FootballerInfo("VLAHOVIC", "Serbia", "https://flagsapi.com/RS/flat/64.png"),
    FootballerInfo("NKUNKU", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("MERINO", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("PAVLIDIS", "Greece", "https://flagsapi.com/GR/flat/64.png"),
    FootballerInfo("DUMFRIES", "Netherlands", "https://flagsapi.com/NL/flat/64.png"),

    FootballerInfo("CUCURELLA", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("MARQUINHOS", "Brazil", "https://flagsapi.com/BR/flat/64.png"),
    FootballerInfo("STANISIC", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("GUENDOUZI", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("JESUS", "Brazil", "https://flagsapi.com/BR/flat/64.png"),

    FootballerInfo("VICARIO", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("SANE", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("ELLIOTT", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("BAKAYOKO", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("NERES", "Brazil", "https://flagsapi.com/BR/flat/64.png"),

    FootballerInfo("CHEVALIER", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("ZIRKZEE", "Netherlands", "https://flagsapi.com/NL/flat/64.png"),
    FootballerInfo("MATETA", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("DALOT", "Portugal", "https://flagsapi.com/PT/flat/64.png"),
    FootballerInfo("BENTANCUR", "Uruguay", "https://flagsapi.com/UY/flat/64.png"),

    FootballerInfo("PALHINHA", "Portugal", "https://flagsapi.com/PT/flat/64.png"),
    FootballerInfo("COMAN", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("TAH", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("DANILO", "Portugal", "https://flagsapi.com/PT/flat/64.png"),
    FootballerInfo("TRUBIN", "Ukraine", "https://flagsapi.com/UA/flat/64.png"),

    FootballerInfo("SANCHO", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("BAILEY", "Jamaica", "https://flagsapi.com/JM/flat/64.png"),
    FootballerInfo("MOUNT", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("AKANJI", "Switzerland", "https://flagsapi.com/CH/flat/64.png"),
    FootballerInfo("IWOBI", "Nigeria", "https://flagsapi.com/NG/flat/64.png"),

    FootballerInfo("GREALISH", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("ANGUISSA", "Cameroon", "https://flagsapi.com/CM/flat/64.png"),
    FootballerInfo("SCHICK", "Czech Republic", "https://flagsapi.com/CZ/flat/64.png"),
    FootballerInfo("DRAGUSIN", "Romania", "https://flagsapi.com/RO/flat/64.png"),
    FootballerInfo("GUESSAND", "France", "https://flagsapi.com/FR/flat/64.png"),

    FootballerInfo("ZHEGROVA", "Kosovo", "https://flagsapi.com/XK/flat/64.png"),
    FootballerInfo("BISSOUMA", "Mali", "https://flagsapi.com/ML/flat/64.png"),
    FootballerInfo("SARR", "Senegal", "https://flagsapi.com/SN/flat/64.png"),
    FootballerInfo("RASPADORI", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("PAVARD", "France", "https://flagsapi.com/FR/flat/64.png"),

    FootballerInfo("OYARZABAL", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("MAZRAOUI", "Morocco", "https://flagsapi.com/MA/flat/64.png"),
    FootballerInfo("SVILAR", "Slovenia", "https://flagsapi.com/SI/flat/64.png"),
    FootballerInfo("MALEN", "Netherlands", "https://flagsapi.com/NL/flat/64.png"),
    FootballerInfo("LLORENTE", "Spain", "https://flagsapi.com/ES/flat/64.png"),

    FootballerInfo("SORLOTH", "Norway", "https://flagsapi.com/NO/flat/64.png"),
    FootballerInfo("LAIMER", "Austria", "https://flagsapi.com/AT/flat/64.png"),
    FootballerInfo("LOBOTKA", "Slovakia", "https://flagsapi.com/SK/flat/64.png"),
    FootballerInfo("BRANDT", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("STONES", "England", "https://flagsapi.com/GB/flat/64.png"),

    FootballerInfo("RABIOT", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("MAIGNAN", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("AKE", "Netherlands", "https://flagsapi.com/NL/flat/64.png"),
    FootballerInfo("SARA", "Brazil", "https://flagsapi.com/BR/flat/64.png"),
    FootballerInfo("LUCUMI", "Colombia", "https://flagsapi.com/CO/flat/64.png"),

    FootballerInfo("GNABRY", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("GORETZKA", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("TROSSARD", "Belgium", "https://flagsapi.com/BE/flat/64.png"),
    FootballerInfo("LUKAKU", "Belgium", "https://flagsapi.com/BE/flat/64.png"),
    FootballerInfo("FELIX", "Portugal", "https://flagsapi.com/PT/flat/64.png"),

    FootballerInfo("ZINCHENKO", "Ukraine", "https://flagsapi.com/UA/flat/64.png"),
    FootballerInfo("SON", "South Korea", "https://flagsapi.com/KR/flat/64.png"),
    FootballerInfo("KOVACIC", "Croatia", "https://flagsapi.com/HR/flat/64.png"),
    FootballerInfo("FRED", "Brazil", "https://flagsapi.com/BR/flat/64.png"),
    FootballerInfo("CHIESA", "Italy", "https://flagsapi.com/IT/flat/64.png"),

    FootballerInfo("MAGUIRE", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("STERLING", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("DIGNE", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("FULKRUG", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("CASEMIRO", "Brazil", "https://flagsapi.com/BR/flat/64.png"),

    FootballerInfo("OBLAK", "Slovenia", "https://flagsapi.com/SI/flat/64.png"),
    FootballerInfo("COURTOIS", "Belgium", "https://flagsapi.com/BE/flat/64.png"),
    FootballerInfo("RUDIGER", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("LUNIN", "Ukraine", "https://flagsapi.com/UA/flat/64.png"),
    FootballerInfo("GRIEZMANN", "France", "https://flagsapi.com/FR/flat/64.png"),

    FootballerInfo("CEBALLOS", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("CORREA", "Argentina", "https://flagsapi.com/AR/flat/64.png"),
    FootballerInfo("GURUZETA", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("PENA", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("CARVAJAL", "Spain", "https://flagsapi.com/ES/flat/64.png"),

    FootballerInfo("KOKE", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("ISCO", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("ALABA", "Austria", "https://flagsapi.com/AT/flat/64.png"),
    FootballerInfo("LEMAR", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("MODRIC", "Croatia", "https://flagsapi.com/HR/flat/64.png"),

    FootballerInfo("TOMORI", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("ANGELINO", "Spain", "https://flagsapi.com/ES/flat/64.png"),
    FootballerInfo("MERET", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("ZANIOLO", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("BENNACER", "Algeria", "https://flagsapi.com/DZ/flat/64.png"),

    FootballerInfo("SUCIC", "Slovenia", "https://flagsapi.com/SI/flat/64.png"),
    FootballerInfo("OKAFOR", "Switzerland", "https://flagsapi.com/CH/flat/64.png"),
    FootballerInfo("ZALEWSKI", "Poland", "https://flagsapi.com/PL/flat/64.png"),
    FootballerInfo("PASALIC", "Croatia", "https://flagsapi.com/HR/flat/64.png"),
    FootballerInfo("ZIELINSKI", "Poland", "https://flagsapi.com/PL/flat/64.png"),

    FootballerInfo("POLITANO", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("PELLEGRINI", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("DYBALA", "Argentina", "https://flagsapi.com/AR/flat/64.png"),
    FootballerInfo("SIMEONE", "Argentina", "https://flagsapi.com/AR/flat/64.png"),
    FootballerInfo("HERMOSO", "Spain", "https://flagsapi.com/ES/flat/64.png"),

    FootballerInfo("ZAPPACOSTA", "Italy", "https://flagsapi.com/IT/flat/64.png"),
    FootballerInfo("KOSTIC", "Serbia", "https://flagsapi.com/RS/flat/64.png"),
    FootballerInfo("SOMMER", "Switzerland", "https://flagsapi.com/CH/flat/64.png"),
    FootballerInfo("MKHITARYAN", "Armenia", "https://flagsapi.com/AM/flat/64.png"),
    FootballerInfo("QUANSAH", "Germany", "https://flagsapi.com/DE/flat/64.png"),

    FootballerInfo("RYERSON", "Norway", "https://flagsapi.com/NO/flat/64.png"),
    FootballerInfo("BOEY", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("TUTA", "Brazil", "https://flagsapi.com/BR/flat/64.png"),
    FootballerInfo("XHAKA", "Switzerland", "https://flagsapi.com/CH/flat/64.png"),
    FootballerInfo("SULE", "Germany", "https://flagsapi.com/DE/flat/64.png"),

    FootballerInfo("ORBAN", "Hungary", "https://flagsapi.com/HU/flat/64.png"),
    FootballerInfo("WERNER", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("MAYULU", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("GOTZE", "Germany", "https://flagsapi.com/DE/flat/64.png"),
    FootballerInfo("NEUER", "Germany", "https://flagsapi.com/DE/flat/64.png"),

    FootballerInfo("SKRINIAR", "Slovakia", "https://flagsapi.com/SK/flat/64.png"),
    FootballerInfo("TOLISSO", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("MUKIELE", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("NDOMBELE", "France", "https://flagsapi.com/FR/flat/64.png"),
    FootballerInfo("FOFANA", "France", "https://flagsapi.com/FR/flat/64.png"),

    FootballerInfo("GUEYE", "Senegal", "https://flagsapi.com/SN/flat/64.png"),
    FootballerInfo("MESSI", "Argentina", "https://flagsapi.com/AR/flat/64.png"),
    FootballerInfo("RONALDO", "Portugal", "https://flagsapi.com/PT/flat/64.png"),
    FootballerInfo("VARDY", "England", "https://flagsapi.com/GB/flat/64.png"),
    FootballerInfo("ICARDI", "Argentina", "https://flagsapi.com/AR/flat/64.png")
    )